set t=%~1
set tf=%~2
set ext=%~3
:Community
For /l %%c in (1,1,9) do ren "Community - Temp.%t% HDTV Cap.%t%0%%c Spanish.%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% HDTV Cap.%t%%%c Spanish.%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% HDTV Cap.%t%0%%c Spanish [www.pctestrenos.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% HDTV Cap.%t%%%c Spanish [www.pctestrenos.com].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Spanish].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%c][Spanish].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Spanish][www.pctestrenos.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Spanish][www.pctestrenos.com].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Communitty%t%0%%c [www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Communitty%t%%%c [www.newpct.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community%t%0%%c [www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community%t%%%c [www.newpct.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% HDTV Cap.%t%0%%c Spanish [www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% HDTV Cap.%t%%%c Spanish [www.newpct.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Spanish].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Spanish].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap. %t%0%%c][Spanish][www.descargaya.es].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap. %t%%%c][Spanish][www.descargaya.es].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap. %t%0%%c][Spanish].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap. %t%%%c][Spanish].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap. %t%0%%c][Spanish][www.descargaya.es].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap. %t%%%c][Spanish][www.descargaya.es].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap. %t%0%%c][Spanish][www.pctestrenos.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap. %t%%%c][Spanish][www.pctestrenos.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Spanish][www.descargaya.es].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Spanish][www.descargaya.es].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Spanish][www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Spanish][www.newpct.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Espa¤ol Castellano][www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Espa¤ol Castellano][www.newpct.com].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Espa¤ol Castellano].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Espa¤ol Castellano].%ext%" "Community %t%%%c.%ext%"   
For /l %%c in (1,1,9) do ren "Community.%t%X0%%c.HDTV.Xvid.Spanish.By.Ainhdesi.%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community.%t%X%%c.HDTV.Xvid.Spanish.By.Ainhdesi.%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Espa¤ol Castellano].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Espa¤ol Castellano].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Espa¤ol Castellano][www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Espa¤ol Castellano][www.newpct.com].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community%t%0%%c [www.newpct.com].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community%t%%%c [www.newpct.com].%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Comunity %t%0%%c.%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Comunity %t%%%c.%ext%" "Community %t%%%c.%ext%"
For /l %%c in (1,1,9) do ren "Community - Temp.%t% [HDTV][Cap.%t%0%%c][Espaol Castellano].%ext%" "Community %t%0%%c.%ext%"
For /l %%c in (10,1,25) do ren "Community - Temp.%t% [HDTV][Cap.%t%%%c][Espa¤ol Castellano].%ext%" "Community %t%%%c.%ext%"



if not %t% gtr %tf% set /a t=%t%+1 & goto Community